### ISSUE TITLE
Roll out new unified standards to all Flux controllers

### ISSUE THREAD

**Issue by scottrigby** [fluxcd/flux2#1601]
- Part of #1602 
- Depends on https://github.com/fluxcd/pkg/issues/117
- Depends on https://github.com/fluxcd/pkg/issues/118

## Status
Now that https://github.com/fluxcd/pkg/pull/101 is merged, people who have already contributed to Flux controllers built on controller-runtime (and have sufficient knowledge of [K8s API conventions](https://github.com/kubernetes/community/blob/master/contributors/devel/sig-architecture/api-conventions.md)) can already start. Until https://github.com/fluxcd/pkg/issues/117 is merged, we can do this on other controllers by pinning that PR branch from the source controller (`refactor-reconcilers`), and then after merge change back to `main`, and when available, to a tagged revision post-merge.

## Tasks
In PRIORITY order, with linked issues/PRs where applicable, and current status:

- [x] Update kustomize-controller to new unified standards 🎉  (https://github.com/fluxcd/kustomize-controller/issues/663)
- [x] source-controller https://github.com/fluxcd/flux2/issues/1679 🙂 (https://github.com/fluxcd/source-controller/pull/361) 
- [ ] helm-controller https://github.com/fluxcd/helm-controller/issues/303 in progress ⏳
- [x] Update image-automation-controller to new unified standards
- [x] Update image-reflector-controller to new unified standards
- [x] Update notification-controller to new unified standards

Nice to have:
- [ ] https://github.com/fluxcd/flux2/issues/1625 on hold 🚫

**Comment by hiddeco** [comment]
RC releases for all relevant packages have been published:

| Package | Version |
|---|---|
| `github.com/fluxcd/pkg/apis/kustomize` | `v0.3.0-rc.1` |
| `github.com/fluxcd/pkg/apis/meta` | `v0.11.0-rc.1` |
| `github.com/fluxcd/pkg/runtime` | `v0.13.0-rc.1` |

Documentation available at: https://pkg.go.dev/github.com/fluxcd/pkg/runtime@v0.13.0-rc.1

**Comment by scottrigby** [comment]
- #1172 
- foo bar

**Comment by makkes** [comment]
@hiddeco the [only remaining open task](https://github.com/fluxcd/helm-controller/issues/303) is closed. Can we close this issue then, too?

**Comment by stefanprodan** [comment]
We've reshaped the roadmap to be about gradually promoting features and APIs to stable (GA). I'm closing this umbrella issue as it tracks things globally, we're now using milestones to track GA per featureset.
