### ISSUE TITLE
Switch to `tonistiigi/xx` across controllers for cross-platform builds

### ISSUE THREAD

**Issue by hiddeco** [fluxcd/flux2#1910]
https://github.com/tonistiigi/xx allows for cross-compilation from Dockerfiles to any platform using the architecture of the builder, which gives native performance. Using this, the source-controller - which had this changed in https://github.com/fluxcd/source-controller/pull/449 - saw a release build time reduction from 40 minutes to 10 (4x less!).

Given the other controllers struggle with the same long duration, we should port their Dockerfiles to make us of this as well. While doing this, it should be taken into account that the GitHub Action workflows should likely be rewritten to make more efficiently use of the `Dockerfile` during (end-to-end) tests, and could be making use of (commit SHA based) caching and/or a local registry.

This should also still be addressed in the source-controller and image-automation-controller, as documented in https://github.com/fluxcd/source-controller/commit/a871e0b527e03e7e9a0fed0056f8b0499e2914cb and https://github.com/fluxcd/image-automation-controller/commit/64ca8dcc48ede0ce942e7bbce08aed3e33d65e5f.

### To-do

- [x] source-controller https://github.com/fluxcd/source-controller/pull/449
- [x] kustomize-controller https://github.com/fluxcd/kustomize-controller/pull/458
- [x] helm-controller https://github.com/fluxcd/helm-controller/pull/335
- [x] image-automation-controller https://github.com/fluxcd/image-automation-controller/pull/222
- [x] image-reflector-controller https://github.com/fluxcd/image-reflector-controller/pull/178
- [x] notification-controller https://github.com/fluxcd/notification-controller/pull/260

**Comment by hiddeco** [comment]
This has been taken care of a long time ago already.
