### ISSUE TITLE
GA Roadmap

### ISSUE THREAD

**Issue by pjbgf** [fluxcd/flux2#2592]
This is an overarching issue with high-level items we want to accomplish ahead of GA. It goes in a bit more detail and expands  the [high-level roadmap to GA in the website](https://fluxcd.io/roadmap/).

#### Website's high-level items:
- [ ] Adopt Kubernetes [kstatus](https://github.com/kubernetes-sigs/cli-utils/tree/v0.25.0/pkg/kstatus#conditions) standard conditions
- [ ] Standardize events and status conditions metadata 
- [x] [Incident management and troubleshooting guides](https://github.com/fluxcd/website/issues/854)
- [ ] [Developer guides for contributing to and extending Flux](https://github.com/fluxcd/website/issues/855)
- [x] [Cloud specific guides (AWS, Azure, Google Cloud, more?)](https://github.com/fluxcd/website/issues/856)

#### Additional Items
- [ ] Azure Authentication
  - [ ] Consolidate implementation and support Workload Identity
- [ ] Improve test coverage
  - [ ] Cloud-specific implementations (i.e. authentication)
  - [ ] Performance Regression
  - [ ] Resource Utilisation Regression
  - [ ] Cover all features inside each controller (as opposed to some scenarios only being covered at flux2) 
- [ ] Establish Performance Benchmark Baseline
- [ ] Notification Controller potential API Changes
  - [ ]  [Standardize event metadata and notification template](https://github.com/fluxcd/flux2/discussions/1529)
- [x] https://github.com/fluxcd/flux2/issues/2593
- [ ] Garbage Collection
- [x] Security Recommendations (Potentially a CIS Benchmark)

**Comment by stefanprodan** [comment]
We've reshaped the roadmap to be about gradually promoting features and APIs to stable (GA). Some of the items mentioned here are completed, but only for the reconcilers of the GA APIs. I'm for closing this umbrella issue as it tracks things globally, we're now using milestones to track GA per featureset.
