### ISSUE TITLE
API Consolidation

### ISSUE THREAD

**Issue by pjbgf** [fluxcd/flux2#3038]
This is an umbrella issue used to track high-level initiatives in our [Maintainer's Focus board](https://github.com/orgs/fluxcd/projects/6/views/17?layout=board&filterQuery=label%3Aumbrella-issue).

**Pre GA Tasks**
- [ ] Adopt Kubernetes [kstatus](https://github.com/kubernetes-sigs/cli-utils/tree/v0.25.0/pkg/kstatus#conditions) standard conditions
  - [x] https://github.com/fluxcd/flux2/issues/1601
    - [x] https://github.com/fluxcd/source-controller/issues/415
    - [ ] https://github.com/fluxcd/helm-controller/issues/487
    - [x] https://github.com/fluxcd/image-reflector-controller/issues/259
    - [x] https://github.com/fluxcd/kustomize-controller/issues/663
    - [x] https://github.com/fluxcd/notification-controller/issues/376
    - [ ] https://github.com/fluxcd/image-automation-controller/issues/364
- [ ] Standardize events and status conditions metadata
  - [x] https://github.com/fluxcd/flux2/issues/1602
- [ ] Standardize the OpenAPI validation for the toolkit.fluxcd.io CRDs - https://github.com/fluxcd/flux2/issues/2993

**Comment by ghobadimhd** [comment]
Hi, is there any ETA for this?

**Comment by stefanprodan** [comment]
We've reshaped the [roadmap](https://fluxcd.io/roadmap/) to be about gradually promoting features and APIs to stable (GA). Some of the items mentioned here are completed, but only for the GA APIs. I'm for closing this umbrella issue as it tracks things globally, we're now using milestones to track GA per featureset.
