### ISSUE TITLE
Git Improvements

### ISSUE THREAD

**Issue by pjbgf** [fluxcd/flux2#3039]
This is an umbrella issue used to track high-level initiatives in our [Maintainer's Focus board](https://github.com/orgs/fluxcd/projects/6/views/17?layout=board&filterQuery=label%3Aumbrella-issue).

**Pre GA Tasks**
- [ ] https://github.com/fluxcd/pkg/issues/333
- [ ] https://github.com/fluxcd/pkg/issues/245
- [ ] https://github.com/fluxcd/pkg/issues/334
- [ ] https://github.com/fluxcd/flux2/issues/2052

**Post GA Tasks**
- [ ] https://github.com/fluxcd/pkg/issues/335
- [ ] https://github.com/fluxcd/pkg/issues/315
