### ISSUE TITLE
Add support for Azure Workload Identity

### ISSUE THREAD

**Issue by pjbgf** [fluxcd/flux2#3041]
Azure Workload Identity is the next generation of workload contextual authentication, which [replaces the existing Azure Pod Identity](https://cloudblogs.microsoft.com/opensource/2022/01/18/announcing-azure-active-directory-azure-ad-workload-identity-for-kubernetes/).

The features in which Flux has Azure Workload Identity supported and documented:
- [x] OCI Repository Authentication
- [x] Bucket Repository Authentication
- [x] Helm OCI Repository Authentication
- [x] Secrets decryption with Azure KeyVault 
- [x] Container Registry Authentication

Relates to https://github.com/fluxcd/flux2/issues/3003.

**Comment by weisdd** [comment]
@pjbgf If FluxCD team accepts the usage of azidentity v1.3.0-beta.2, then we can quickly add support for Workload Identity to several controllers by bumping deps:

- Support for workload identity was added to github.com/Azure/azure-sdk-for-go/sdk/azidentity in v1.3.0-beta.1 (https://github.com/Azure/azure-sdk-for-go/issues/15615#issuecomment-1350174008). The latest version at the time of writing is v1.3.0-beta.2.
- Even though the "stable" version is expected to be released around April after the Workload Identity extension is promoted to GA (https://github.com/Azure/azure-sdk-for-go/issues/19765#issuecomment-1376512434), the current one is already functional.
- The support for Workload Identity is available through [WorkloadIdentityCredential](https://pkg.go.dev/github.com/Azure/azure-sdk-for-go/sdk/azidentity@v1.3.0-beta.2#WorkloadIdentityCredential) and [DefaultAzureCredential](https://pkg.go.dev/github.com/Azure/azure-sdk-for-go/sdk/azidentity@v1.3.0-beta.2#DefaultAzureCredential).
- In FluxCD source-controller, helm repository controller relies on fluxcd/pkg/oci package to authenticate against ACR when provider is set to `azure`. The package relies on DefaultAzureCredential. So, to add support for Workload Identity there, it's enough to bump dependencies (like [here](https://github.com/fluxcd/pkg/blob/946d9acf6e88cd807ff72119f5f5e96cbd690894/oci/auth/azure/auth.go#L69)). I did a PoC in my sandbox, and it worked just fine (you can find logs below).
- Although I haven't tested it yet, I think some other controllers (like OCI repository controller, image reflector controller) would work as well. Bucket controller has its own logic for authentication, so it'll require some adjustments, but I guess we don't have to modify all controllers at once :)

Please, let me know what you think. If you would accept such change, I can prepare a PR with all the instructions and a terraform test lab.

<details>
<summary>Logs</summary>
source-controller-57774ccfc5-64bvd manager {"level":"info","ts":"2023-01-14T23:33:34.841Z","msg":"logging in to Azure ACR for fluxcdtestacr123.azurecr.io/charts","controller":"helmrepository","controllerGroup":"source.toolkit.fluxcd.io","controllerKind":"HelmRepository","HelmRepository":{"name":"charts","namespace":"flux-system"},"namespace":"flux-system","name":"charts","reconcileID":"8c61bb40-7a54-40a4-b7b0-e3a1fbe9b875"}
source-controller-57774ccfc5-64bvd manager {"level":"info","ts":"2023-01-14T23:33:35.400Z","msg":"Helm repository is ready","controller":"helmrepository","controllerGroup":"source.toolkit.fluxcd.io","controllerKind":"HelmRepository","HelmRepository":{"name":"charts","namespace":"flux-system"},"namespace":"flux-system","name":"charts","reconcileID":"8c61bb40-7a54-40a4-b7b0-e3a1fbe9b875"}
source-controller-57774ccfc5-64bvd manager {"level":"info","ts":"2023-01-14T23:38:35.444Z","msg":"logging in to Azure ACR for fluxcdtestacr123.azurecr.io/charts","controller":"helmrepository","controllerGroup":"source.toolkit.fluxcd.io","controllerKind":"HelmRepository","HelmRepository":{"name":"charts","namespace":"flux-system"},"namespace":"flux-system","name":"charts","reconcileID":"bb59958b-0c44-4b35-871f-f7679c37d097"}
source-controller-57774ccfc5-64bvd manager {"level":"info","ts":"2023-01-14T23:39:01.314Z","msg":"logging in to Azure ACR for fluxcdtestacr123.azurecr.io/charts","controller":"helmchart","controllerGroup":"source.toolkit.fluxcd.io","controllerKind":"HelmChart","HelmChart":{"name":"default-podinfo","namespace":"flux-system"},"namespace":"flux-system","name":"default-podinfo","reconcileID":"a0faa635-370a-4ad8-bb37-e60e16f3607c"}
source-controller-57774ccfc5-64bvd manager {"level":"info","ts":"2023-01-14T23:39:02.021Z","msg":"pulled 'base' chart with version '0.3.2'","controller":"helmchart","controllerGroup":"source.toolkit.fluxcd.io","controllerKind":"HelmChart","HelmChart":{"name":"default-podinfo","namespace":"flux-system"},"namespace":"flux-system","name":"default-podinfo","reconcileID":"a0faa635-370a-4ad8-bb37-e60e16f3607c"}
</details>

**Comment by somtochiama** [comment]
Workload identity has been added in each of the relevant controllers: See: https://github.com/fluxcd/kustomize-controller/pull/813, https://github.com/fluxcd/source-controller/pull/1048, https://github.com/fluxcd/image-reflector-controller/pull/363.

**Comment by Poltergeisen** [comment]
How can we use this for Azure devops git repositories?

**Comment by hatfarm** [comment]
@Poltergeisen I was wondering the same thing!  Have you figured it out?  I don't think there's a way, currently, to do it.  I've thought about putting together a PR, but am not familiar with Go (I AM pretty familiar with the AZDO method of hooking this up).

**Comment by aryan9600** [comment]
Hello, support for Azure Devops Git repositories is planned and being worked on.

**Comment by hatfarm** [comment]
@aryan9600 Is this something I can help with?  Anything I can follow a little closer?  I would love to get involved, but mostly want to be aware of when this might be landing.

**Comment by somtochiama** [comment]
Hey @andywilde ,

That documentation is outdated and we will update it. Thanks for pointing it out.
If you have setup workload identity on your aks cluster and have labelled the image-reflector-controller and pod correctly, workload identity should work. The only extra you need is `provider: azure` in your `ImageRepository` manifest.

**Comment by andywilde** [comment]
Hi @somtochiama,  do you have an example of ImageRepository? With this code:
```
apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImageRepository
metadata:
  name: podinfo
  namespace: flux-system
spec:
  image: xxx.azurecr.io/stefanprodan/podinfo
  interval: 5m0s
  provider: azure
```
I get the error `.spec.provider: field not declared in schema`.  Does API version require an update?

**Comment by somtochiama** [comment]
yes, what version of flux are you on?

**Comment by andywilde** [comment]
2.0.0

**Comment by andywilde** [comment]
I guess this errors mean the authentication is fixed but I have to configure something else?
```
{"level":"error","ts":"2023-10-13T16:17:05.213Z","msg":"referenced ImageRepository has not been scanned yet","controller":"imagepolicy","controllerGroup":"image.toolkit.fluxcd.io","controllerKind":"ImagePolicy","ImagePolicy":{"name":"podinfo","namespace":"flux-system"},"namespace":"flux-system","name":"podinfo","reconcileID":"8051531b-7e30-4c65-a653-5fff7df48e54","error":"DependencyNotReady"}
```

**Comment by somtochiama** [comment]
what do you see when you run `flux get image repository`?

**Comment by andywilde** [comment]
The error was `No matching federated identity record found for presented assertion` so I created federated credential on the MI mapped to  `system:serviceaccount:flux-system:image-reflector-controller` and that seemed to do the trick. Output from `flux get image repository` is now:
```
NAME    LAST SCAN               SUSPENDED       READY   MESSAGE
podinfo 2023-10-13T16:45:12Z    False           True    successful scan: found 4 tags
```

With this working and based on the images in our ACR:
![image](https://github.com/fluxcd/flux2/assets/118730699/8ef4451a-b3b5-4d25-b200-649896b7ccf0)

I was expecting the image in the HR release to be updated in the git repo from
```
 image:
      repository: xxx.azurecr.io/stefanprodan/podinfo
      tag: 6.4.0
      pullPolicy: Always
```
to `6.5.0`

I guess this means I need to configure something else?

**Comment by somtochiama** [comment]
Do you have image automation set up? https://fluxcd.io/flux/guides/image-update/

**Comment by andywilde** [comment]
It's working now. The problem was I hadn't added the policy marker:
```
tag: 6.4.0 # {"$imagepolicy": "flux-system:podinfo:tag"}
```
@somtochiama thanks for all your help. Have a great weekend!

**Comment by Poltergeisen** [comment]
> Hello, support for Azure Devops Git repositories is planned and being worked on.

@aryan9600 do you happen to know how long it might take? Or is there an issue I can subscribe to that tracks that functionality?

**Comment by b-rand** [comment]
> > Hello, support for Azure Devops Git repositories is planned and being worked on.
> 
> @aryan9600 do you happen to know how long it might take? Or is there an issue I can subscribe to that tracks that functionality?

@aryan9600 bumping this question back up to you since this is a topic of interest for my team as well.

**Comment by aryan9600** [comment]
@Poltergeisen @b-rand hello, i was on vacation and then busy with kubecon. i have resumed work on this. the PR which enables support for this is: https://github.com/fluxcd/pkg/pull/664. there's a lot of work still remaining before the new package can be used in the controllers. i'm targeting the next to next minor release of flux, i.e. flux v2.3.0
