### ISSUE TITLE
Prepare for v0.35 release

### ISSUE THREAD

**Issue by stefanprodan** [fluxcd/flux2#3155]
The 0.35 release comes with a new feature in Flux: **Cosign verification of OCI artifacts** (part of [RFC-0003](https://github.com/fluxcd/flux2/tree/main/rfcs/0003-kubernetes-oci)).

Release checklist:
- [x] source-controller v0.30.0
- [x] kustomize-controller v0.29.0
- [x] helm-controller v0.24.0
- [x] notification-controller v0.27.0
- [x] image-reflector-controller v0.22.0
- [x] image-automation-controller v0.26.0
- [x] flux2 v0.35.0
- [x] terraform-provider-flux v0.19.0

Documentation updates:
- [x] Add Cosign keyless specification to RFC-0003 [flux2#3154](https://github.com/fluxcd/flux2/pull/3154)
- [x] Add Cosign signing and Flux verification to the OCI docs [website#1167](https://github.com/fluxcd/website/pull/1167)
- [x]  Publish Flux release change log to GitHub & Slack
