### ISSUE TITLE
Prepare for v0.36 release

### ISSUE THREAD

**Issue by stefanprodan** [fluxcd/flux2#3228]
The 0.36 release comes with a new feature in Flux: **Cosign verification of Helm OCI charts**.

TODOs:
- [x] update `golang.org/x/text` in all controllers and CLI (fix CVE-2022-32149)
- [x] https://github.com/fluxcd/source-controller/pull/937
- [x] https://github.com/fluxcd/source-controller/pull/925
- [x] https://github.com/fluxcd/helm-controller/pull/545

Release checklist:
- [x] source-controller v0.31.0
- [x] kustomize-controller v0.30.0
- [x] helm-controller v0.26.0
- [x] notification-controller v0.28.0
- [x] image-reflector-controller v0.22.1
- [x] image-automation-controller v0.26.1
- [x] flux2 v0.36.0
- [x] terraform-provider-flux v0.20.0

Documentation updates:
- [x] Add Cosign verification specification to RFC-0002
- [x] Add Cosign verification to the Helm OCI docs 
- [x]  Publish Flux release change log to GitHub & Slack
