### ISSUE TITLE
Bootstrap GA

### ISSUE THREAD

**Issue by pjbgf** [fluxcd/flux2#3274]
This umbrella issue tracks the work required to GA the components, APIs and commands involved in Flux bootstrapping.

### APIs promotion to GA
- https://github.com/fluxcd/source-controller/issues/947
- https://github.com/fluxcd/kustomize-controller/issues/755
- https://github.com/fluxcd/notification-controller/issues/436

### Controllers promotion to GA
- [ ] source-controller v1.0.0
- [ ] kustomize-controller v1.0.0
- [ ] notification-controller v1.0.0

### CLI commands promotion to GA
- [x] `flux bootstrap *`
- [x] `flux <action> gitrepository`
- [x] `flux <action> kustomization`
- [x] `flux <action> recevier`

**Comment by makkes** [comment]
Tagging fluxcd/flux2 with v2 forces us to change the module path to github.com/fluxcd/flux2/v2 and all consumers need to change their imports and add the /v2 suffix.

**Comment by stefanprodan** [comment]
Closing this, we'll track the controller releases in a dedicated issue.
