### ISSUE TITLE
Prepare for v0.38 release

### ISSUE THREAD

**Issue by stefanprodan** [fluxcd/flux2#3344]
The 0.38 release promotes to Notification API to **v1beta2** and introduces experimental support for Kustomize components.

TODOs:
- [x] https://github.com/fluxcd/notification-controller/pull/435
- [x] https://github.com/fluxcd/kustomize-controller/pull/754
- [x] https://github.com/fluxcd/image-automation-controller/pull/463
- [x] https://github.com/fluxcd/source-controller/pull/975
- [x] https://github.com/fluxcd/helm-controller/pull/570
- [x] https://github.com/fluxcd/flux2/pull/3377
- [x] https://github.com/fluxcd/flux2/pull/3389
- [x] https://github.com/fluxcd/source-controller/issues/951
- [x] https://github.com/fluxcd/image-automation-controller/pull/470
- [ ] https://github.com/fluxcd/image-automation-controller/pull/469

Release checklist:
- [x] source-controller v0.33.0
- [ ] image-automation-controller v0.28.0
- [x] image-reflector-controller v0.23.1
- [x] kustomize-controller v0.32.0
- [x] notification-controller v0.30.0
- [x] helm-controller: v0.28.0
- [x] flux2 v0.38.0
- [x] terraform-provider-flux v0.22.0

Documentation updates:
- [x] [Persistent storage for Flux internal artifacts](https://github.com/fluxcd/website/pull/1308)
- [x] [Update the website docs script to Notification API v1beta2 URLs](https://github.com/fluxcd/website/pull/1335)
- [x] [Update the notifications and webhook receivers guides to v1beta2](https://github.com/fluxcd/website/pull/1335)
- [x] Publish Flux release change log to GitHub & Slack
