### ISSUE TITLE
Prepare for v0.39 release

### ISSUE THREAD

**Issue by stefanprodan** [fluxcd/flux2#3533]
The 0.39 release comes with SBOMs and SLSA Provenance attached to all the controllers container images. In addition, all controller images have been update to Alpine 3.17 (which contains CVE fixes for OS packages). Starting with this version, the Flux controllers should consume less memory on busy clusters due to the disabling of Secrets and ConfigMaps caching.

TODOs:
- [x] https://github.com/fluxcd/flux2/issues/3522
- [x] https://github.com/fluxcd/flux2/issues/3426
- [x] https://github.com/fluxcd/pkg/pull/442
- [x] https://github.com/fluxcd/kustomize-controller/pull/787
- [x] https://github.com/fluxcd/flux2/pull/3540

Release checklist:
- [x] source-controller v0.34.0
- [x] kustomize-controller v0.33.0
- [x] notification-controller v0.31.0
- [x] helm-controller: v0.29.0
- [x] image-automation-controller v0.29.0
- [x] image-reflector-controller v0.24.0
- [x] flux2 v0.39.0
- [x] terraform-provider-flux v0.23.0

Documentation updates:
- [x] Document `CacheSecretsAndConfigMaps` feature gate
- [x] Add SBOMs, SLSA Provenance and CVE scanning to https://fluxcd.io/flux/security/
- [x] Publish Flux release change log to GitHub & Slack
