### ISSUE TITLE
Update Go to v1.20

### ISSUE THREAD

**Issue by stefanprodan** [fluxcd/flux2#3559]
Update Go to 1.20 in GH Workflows and Dockerfiles for:
- [x] pkg
- [x] source-controller
- [x] source-watcher
- [x] kustomize-controller
- [x] notification-controller
- [x] helm-controller
- [x] image-automation-controller 
- [x] image-reflector-controller
- [x] flux2
- [x] terraform-provider-flux

**Comment by hiddeco** [comment]
Think this is actually scheduled for next MINOR.
