### ISSUE TITLE
Update Flux controllers to Kustomize v5.0

### ISSUE THREAD

**Issue by stefanprodan** [fluxcd/flux2#3564]
We should update Flux to Kustomize to [v5.0.0](https://github.com/kubernetes-sigs/kustomize/releases/tag/kustomize%2Fv5.0.0) but this version comes with many breaking changes. One breaking change is the removal of the `DoLegacyResourceSort` which is used in Kubernetes [cli-runtime](https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/cli-runtime/pkg/resource/kustomizevisitor.go#L41), given that kustomize-controller depends on `cli-runtime` we are in stuck with Kustomize v4 until there is an official Kubernetes release that includes the Kustomize v5 in `cli-runtime`.

Bumping `sigs.k8s.io/kustomize/api` to `v0.13.1` in kustomize-controller results in:

```
# k8s.io/cli-runtime/pkg/resource
../../../../pkg/mod/k8s.io/cli-runtime@v0.26.1/pkg/resource/kustomizevisitor.go:41:8:
kOpts.DoLegacyResourceSort undefined (type *krusty.Options has no field or method DoLegacyResourceSort)
```

Use `kustomize/api@v0.13.1` and `kustomize/kyaml@v0.14.0` in:
- [ ] fluxcd/pkg
- [ ] fluxcd/kustomize-controller
- [ ] fluxcd/helm-controller
- [ ] fluxcd/image-automation-controller
- [ ] fluxcd/flux2

**Comment by stefanprodan** [comment]
This has been [fixed upstream](https://github.com/kubernetes/kubernetes/pull/116598), Kustomize v5 will be shipped in Kubernetes 1.27 next week. After the release we can look into updating Flux.

**Comment by stefanprodan** [comment]
We don't know yet. While Kubernetes cli-runtime was update, the Kubernetes cli-utils is still on the old Kustomize version https://github.com/kubernetes-sigs/cli-utils/blob/ed4ec48b3405206c6c2200adbbc9606ea46b4257/go.mod#L95

**Comment by stefanprodan** [comment]
We've started the upgrade, currently blocked by controller-runtime, ref: https://github.com/fluxcd/pkg/pull/534

**Comment by stefanprodan** [comment]
We are now waiting on https://github.com/kubernetes-sigs/controller-runtime/issues/2297 that depends on Kubernetes 1.27.2 (scheduled for 17th May).

**Comment by stefanprodan** [comment]
This is now done and will be part of Flux v2.0.0-rc.4 release
