### ISSUE TITLE
Prepare for v0.40 release

### ISSUE THREAD

**Issue by stefanprodan** [fluxcd/flux2#3567]
The 0.40 release promotes the `ImageRepository` and `ImagePolicy` APIs to **v1beta2** and deprecates the auto-login controller flags. In addition, the source revision format changes as described by [RFC-0005](https://github.com/fluxcd/flux2/tree/main/rfcs/0005-artifact-revision-and-digest).

TODOs:
- [ ] https://github.com/fluxcd/image-reflector-controller/pull/311
- [ ] https://github.com/fluxcd/source-controller/pull/1001
- [ ] https://github.com/fluxcd/source-controller/pull/1020
- [ ] https://github.com/fluxcd/flux2/issues/3559
- [ ] https://github.com/fluxcd/flux2/pull/3566

Release checklist:
- [ ] source-controller v0.35.0
- [ ] kustomize-controller v0.34.0
- [ ] notification-controller v0.32.0
- [ ] helm-controller: v0.30.0
- [ ] image-automation-controller v0.30.0
- [ ] image-reflector-controller v0.25.0
- [ ] flux2 v0.40.0
- [ ] terraform-provider-flux v0.24.0

Documentation updates:
- [ ] Replace the AWS, Azure, GCP auto-login flags with `ImageRepository.spec.provider` in guides
- [ ] Update the revision format in all guides
- [ ] Publish Flux release change log to GitHub & Slack
