### ISSUE TITLE
Make all project controllers private

### ISSUE THREAD

**Issue by aryan9600** [fluxcd/flux2#3719]
Kubebuilder v4 is changing its project directory to have controllers in the `internal` dir (ref: https://github.com/kubernetes-sigs/kubebuilder/tree/7f5d552d315413cbc4d18cf812e173c4f8311d2c/docs/book/src/cronjob-tutorial/testdata/project/internal/controller). We should adopt this change for all our controllers:

- [ ] fluxcd/source-controller
- [x] fluxcd/helm-controller
- [x] fluxcd/kustomize-controller
- [x] fluxcd/notification-controller
- [x] fluxcd/image-reflector-controller
- [x] fluxcd/image-automation-controller

**Comment by makkes** [comment]
re-opening as SC hasn't been tackled, yet.
