### ISSUE TITLE
Prepare for Flux v2.0.0-rc.1

### ISSUE THREAD

**Issue by stefanprodan** [fluxcd/flux2#3735]
The fist release candidate of Flux GA comes with the promotion of the bootstrap related APIs to v1 and adds horizontal scaling & sharding capabilities to Flux controllers. In addition, this prerelease comes with support for auth with Azure Workload Identity.

TODOs:
- https://github.com/fluxcd/source-controller/issues/947
- https://github.com/fluxcd/kustomize-controller/issues/755
- https://github.com/fluxcd/notification-controller/issues/436
- https://github.com/fluxcd/flux2/issues/3731
- https://github.com/fluxcd/flux2/issues/3719
- https://github.com/fluxcd/source-controller/pull/1048
- https://github.com/fluxcd/kustomize-controller/pull/813
- https://github.com/fluxcd/helm-controller/pull/659
- https://github.com/fluxcd/helm-controller/pull/660
- https://github.com/fluxcd/flux2/issues/3695
- #3737
- #3739
- https://github.com/fluxcd/flux2/pull/3654
- fluxcd/source-watcher#52
- https://github.com/fluxcd/flux2/pull/3758

Release checklist:
- [x] source-controller v1.0.0-rc.1
- [x] kustomize-controller v1.0.0-rc.1
- [x] notification-controller v1.0.0-rc.1
- [x] helm-controller: v0.32.0
- [x] image-reflector-controller v0.27.0
- [x] image-automation-controller v0.32.0
- [x] flux2 v2.0.0-rc.1
- [x] terraform-provider-flux v1.0.0-rc.1
- [x] source-watcher v1.0.0-rc.1

Documentation updates:
- [ ] fluxcd/website#1453
- [x] [Add the sharding flag to controller docs](https://github.com/fluxcd/website/pull/1427)
- [x] [Document how to configure sharding](https://github.com/fluxcd/website/pull/1444)
- [x] [Update the API spec docs to v1](https://github.com/fluxcd/website/pull/1427)
- [x] [Update all docs pages to v1](https://github.com/fluxcd/website/pull/1427)
- [x] Publish Flux release change log to GitHub & Slack
