### ISSUE TITLE
Prepare for Flux v2.0.0-rc.2

### ISSUE THREAD

**Issue by stefanprodan** [fluxcd/flux2#3842]
The 2nd release candidate of Flux GA comes with bug fixes and improvements. This release marks source-controller, kustomize-controller and helm-controller as [system-cluster-critical](https://kubernetes.io/docs/tasks/administer-cluster/guaranteed-scheduling-critical-addon-pods/). This priority class will reduce the chances of Flux controllers being evicted before other non-critical workloads and prevents the pods from being permanently unavailable.

TODOs:
- https://github.com/fluxcd/flux2/pull/3795
- https://github.com/fluxcd/flux2/pull/3802
- https://github.com/fluxcd/flux2/pull/3821
- https://github.com/fluxcd/kustomize-controller/pull/838
- https://github.com/fluxcd/notification-controller/pull/506
- https://github.com/fluxcd/notification-controller/pull/508
- https://github.com/fluxcd/notification-controller/pull/515
- https://github.com/fluxcd/image-automation-controller/pull/510
- https://github.com/fluxcd/helm-controller/pull/672
- https://github.com/fluxcd/helm-controller/pull/673

Release checklist:
- [x] source-controller v1.0.0-rc.2
- [x] kustomize-controller v1.0.0-rc.2
- [x] notification-controller v1.0.0-rc.2
- [x] helm-controller: v0.32.2
- [x] image-reflector-controller v0.27.1
- [x] image-automation-controller v0.33.0
- [x] flux2 v2.0.0-rc.2
- [ ] terraform-provider-flux v1.0.0-rc.2

Documentation:
- [x] Publish Flux release change log to GitHub & Slack
