### ISSUE TITLE
Prepare for Flux v2.0.0-rc.3

### ISSUE THREAD

**Issue by stefanprodan** [fluxcd/flux2#3881]
The 3nd release candidate of Flux GA comes with bug fixes and improvements. The controllers base image have been update to Alpine 3.18 and patches for CVE-2023-2253 and CVE-2023-1732 have been applied to all Flux components. 

RC.3 fixes a regression bug introduced in RC.2 that prevented the Flux controllers from running on GKE due to insufficient quota for critical pods.

TODOs:
- https://github.com/fluxcd/flux2/pull/3879
- https://github.com/fluxcd/source-controller/pull/1094
- https://github.com/fluxcd/source-controller/pull/1088
- https://github.com/fluxcd/notification-controller/pull/519
- https://github.com/fluxcd/helm-controller/pull/684
- https://github.com/fluxcd/flux2/pull/3880
- https://github.com/fluxcd/image-reflector-controller/pull/374

Release checklist:
- [x] source-controller v1.0.0-rc.3
- [x] kustomize-controller v1.0.0-rc.3
- [x] notification-controller v1.0.0-rc.3
- [x] helm-controller: v0.33.0
- [x] image-reflector-controller v0.27.2
- [x] image-automation-controller v0.33.1
- [x] flux2 v2.0.0-rc.3
- [ ] terraform-provider-flux v1.0.0-rc.3

Documentation:
- [ ] Publish Flux release change log to GitHub & Slack
