### ISSUE TITLE
Update Flux components to Kubernetes controller-runtime v0.15

### ISSUE THREAD

**Issue by stefanprodan** [fluxcd/flux2#3907]
Update the GitOps Toolkit packages and the Flux controllers to Kubernetes 1.27, controller-runtime v0.15 and controller-gen v0.12.

Adapt the controller code to the breaking changes introduced in controller-runtime **v0.15**:
* `Watches` require a plain `client.Object` instead of a `source.Kind` object.
* `handler.MapFunc` requires a Go context.
* `ctrlcache.Options.SelectorByObject` was renamed to `ctrlcache.Options.ByObject`.
* `ctrl.Options.Namespace` was moved to `ctrlcache.Options.Namespaces`.
* `ctrl.Options.ClientDisableCacheFor` was moved to `ctrlclient.CacheOptions.DisableFor`.
* `ctrl.Options.Port` has been deprecated and removed.

TODOs:
- [x] fluxcd/pkg https://github.com/fluxcd/pkg/pull/534
- [ ] source-controller
- [ ] kustomize-controller
- [ ] notification-controller
- [ ] helm-controller
- [ ] image-reflector-controller
- [ ] image-automation-controller
