### ISSUE TITLE
Prepare for Flux v2.0.0-rc.4

### ISSUE THREAD

**Issue by stefanprodan** [fluxcd/flux2#3911]
The 4nd release candidate of Flux GA comes with support for Kubernetes 1.27, Kustomize 5.0, Helm 3.12 and Cosign 2.0.

⚠️ Note that Kustomize v5 contains breaking changes, please consult their [changelog](https://github.com/kubernetes-sigs/kustomize/releases/tag/kustomize%2Fv5.0.0) for more details.

The GitOps Toolkit and the Flux controllers have been updated to [controller-runtime v0.15](https://github.com/kubernetes-sigs/controller-runtime/releases/tag/v0.15.0) which contains breaking changes that could affect 3rd-party controllers that integrate with Flux. 

Flux dependencies have been updated to patch the following vulnerabilities:
- CVE-2023-28840 (Docker)
- CVE-2023-28841 (Docker)
- CVE-2023-28842 (Docker)
- CVE-2023-30551 (Sigstore Rekor)

TODOs:
- https://github.com/fluxcd/flux2/issues/3564
- https://github.com/fluxcd/flux2/issues/3907
- https://github.com/fluxcd/source-controller/pull/1096
- https://github.com/fluxcd/notification-controller/pull/517
- https://github.com/fluxcd/notification-controller/pull/529
- https://github.com/fluxcd/notification-controller/pull/530
- https://github.com/fluxcd/notification-controller/pull/534
- https://github.com/fluxcd/helm-controller/pull/692
- https://github.com/fluxcd/pkg/issues/546
- https://github.com/fluxcd/pkg/pull/560
- https://github.com/fluxcd/pkg/pull/563
- https://github.com/fluxcd/flux2-kustomize-helm-example/pull/97
- https://github.com/fluxcd/flux2/pull/3675
- https://github.com/fluxcd/flux2/pull/3918

Release checklist:
- [x] source-controller v1.0.0-rc.4
- [x] kustomize-controller v1.0.0-rc.4
- [x] notification-controller v1.0.0-rc.4
- [x] helm-controller: v0.34.0
- [x] image-reflector-controller v0.28.0
- [x] image-automation-controller v0.34.0
- [x] flux2 v2.0.0-rc.4
- [x] terraform-provider-flux v1.0.0-rc.4

Documentation:
- [x] Publish Flux release change log to GitHub & Slack
- [x] Update Kustomize references in docs to v5
