### ISSUE TITLE
Generate SLSA3 provenance for all Flux components 

### ISSUE THREAD

**Issue by stefanprodan** [fluxcd/flux2#3994]
All the GitOps Toolkit controllers and the Flux CLI should make use of the [SLSA GitHub Generator](https://github.com/slsa-framework/slsa-github-generator) at release time for generating non-forgeable SLSA provenance on GitHub that meets the [provenance generation](https://slsa.dev/spec/v1.0/requirements#provenance-generation) and [isolation](https://slsa.dev/spec/v1.0/requirements#isolation-strength) requirements for [SLSA Build level 3 and above](https://slsa.dev/spec/v1.0/levels).

Generators:
- `generator_generic_slsa3` for the release assets (binaries, SBOMs, source code)
- `generator_container_slsa3` for the multi-arch container images (DockerHub and GHCR)

Add the SLSA3 generators to the following release workflows:
- [x] source-watcher
- [x] source-controller 
- [x] kustomize-controller 
- [x] notification-controller 
- [x] helm-controller
- [x] image-reflector-controller 
- [x] image-automation-controller
- [x] flux2
- [x] terraform-provider-flux
