### ISSUE TITLE
Prepare for Flux v2.0.0

### ISSUE THREAD

**Issue by stefanprodan** [fluxcd/flux2#4013]
After three months and five release candidates we are finally ready to release Flux 2.0.0 🎉  Big thanks to all the Flux users who have tested the release candidates and helped us polish the [GitOps features](https://fluxcd.io/roadmap/#flux-gitops-ga-q2-2023) of Flux and its GitOps related APIs.

The Flux v2.0.0 release comes with fixes to issues reported for 2.0.0-rc.5.

In addition, Flux v2.0.0 comes with enhancements to its build and release process by adopting the Supply Chain Levels for Software Artifacts (SLSA) [provenance generators](https://github.com/slsa-framework/slsa-github-generator). Starting with v.2.0.0, Flux provisionally meets the [SLSA Level 3](https://slsa.dev/spec/v1.0/levels) requirements. Flux users will be able to verify the provenance of Flux release artifacts ((binaries, container images, SBOMs, deploy manifests, source code) using the official [SLSA verifier tool](https://github.com/slsa-framework/slsa-verifier). 

TODOs:
- https://github.com/fluxcd/flux2/pull/3254
- https://github.com/fluxcd/flux2/pull/4020
- https://github.com/fluxcd/flux2/issues/3994
- https://github.com/fluxcd/website/pull/1530
- https://github.com/fluxcd/flux2/issues/4014
- https://github.com/fluxcd/flux2/issues/4022
- https://github.com/fluxcd/flux2/pull/3755
- https://github.com/fluxcd/website/pull/1538
- https://github.com/fluxcd/terraform-provider-flux/pull/506

Release checklist:
- [x] source-controller v1.0.0
- [x] source-watcher v1.0.0
- [x] kustomize-controller v1.0.0
- [x] notification-controller v1.0.0
- [x] helm-controller: v0.35.0
- [x] image-reflector-controller v0.29.0
- [x] image-automation-controller v0.35.0
- [x] flux2 v2.0.0
- [x] terraform-provider-flux v1.0.0

Documentation:
- [x] Publish Flux release change log to GitHub & Slack
- [x] Publish Flux release specifications and long-term support pledge 
- [x] Publish assessment of SLSA Level 3 requirements

**Comment by SebTardif** [comment]
Any UI is expected to be compatible soon with Flux v2.0.0?

Recently, when trying the plug-in in VSCode failed. Should probably make sure the FAQ doesn't give the impression any GUI exist if the user is using Flux v2.

**Comment by makkes** [comment]
@SebTardif All UIs listed at https://fluxcd.io/flux/#flux-uis should work with the latest Flux version. If they don't, please submit issues in the respective places.

**Comment by juozasg** [comment]
> @SebTardif All UIs listed at https://fluxcd.io/ecosystem/#flux-uis--guis should work with the latest Flux version. If they don't, please submit issues in the respective places.

Hi, I've been developing new features for the vscode extension using v2.0.0-rc.5. Haven't seen any problems. Can you provide more information please?

**Comment by salekseev** [comment]
https://github.com/fluxcd/flux2/pkgs/container/flux-manifests still does not have a `v2.0.0` tag published.

**Comment by stefanprodan** [comment]
@salekseev yes our release workflow failed just before the OCI push, we'll do a patch release 2.0.1 tomorrow.

**Comment by stefanprodan** [comment]
@salekseev to unblock you, I have pushed the manifest image and signed it myself.
