### ISSUE TITLE
Update Flux components to Go 1.20 in `go.mod` and `oss-fuzz`

### ISSUE THREAD

**Issue by stefanprodan** [fluxcd/flux2#4014]
To align the Go version with Kubernetes and controller-runtime, we need to bump Go to 1.20 in all APIs `go.mod`, all controllers `go.mod` and all packages `go.mod`. We also have to install Go 1.20 in all oss-fuzz Dockerfiles as the base image comes with 1.19.

TODO:
- [x] pkg
- [x] source-watcher
- [x] source-controller 
- [x] kustomize-controller 
- [x] notification-controller 
- [x] helm-controller
- [x] image-reflector-controller 
- [x] image-automation-controller
- [x] flux2
- [x] terraform-provider-flux
