### ISSUE TITLE
Prepare for Flux v2.0.1

### ISSUE THREAD

**Issue by stefanprodan** [fluxcd/flux2#4049]
Flux v2.0.1 is a patch release that comes with fixes to issues reported by users who upgraded to v2.0.0.

:date: **Target dates:** 10-13 July 2023

Fixes:
- [x] AWS auth failing for cross-region  ECR repositories ([source-controller#1158](https://github.com/fluxcd/source-controller/pull/1158), [image-reflector-controller#417](https://github.com/fluxcd/image-reflector-controller/pull/417))
- [x] Spurious alerts for skipped resources ([kustomize-controller#920](https://github.com/fluxcd/kustomize-controller/pull/920))
- [x] SLSA provenance files missing for the Flux CLI binaries ([flux2#4041](https://github.com/fluxcd/flux2/pull/4041), [flux2#4043](https://github.com/fluxcd/flux2/pull/4043))
- [x] https://github.com/fluxcd/flux2/issues/3733

Improvements to Flux GitHub Action ([flux2#4043](https://github.com/fluxcd/flux2/pull/4051), [flux2#4061](https://github.com/fluxcd/flux2/pull/4061), [flux2#4065](https://github.com/fluxcd/flux2/pull/4065)):
- Add support for MacOS and Windows Github runners.
- Verify the SHA256 of the Flux CLI archive against the checksum file published together with the release.
- Add the Flux CLI binary to the GitHub runner cache.
- Deprecate the `arch` input which is now auto detected from the runner env. 
- Add e2e tests for the Flux Action on Linux, MacOS and Windows runners.

To use the improved action refer it from `main` or pin it to the commit:
- `fluxcd/flux2/action@main`
- `fluxcd/flux2/action@e88577fe52a711975a0382818b60de01b7ad22f8`

The Flux GitHub Action documentation is now available at https://fluxcd.io/flux/flux-gh-action/.

Release checklist:
- [x] source-controller v1.0.1
- [x] kustomize-controller v1.0.1
- [x] image-reflector-controller v0.29.1
- [x] flux2 v2.0.1
- [x] terraform-provider-flux v1.0.1
