### ISSUE TITLE
API docs versioning

### ISSUE THREAD

**Issue by makkes** [fluxcd/flux2#4111]
As part of our [long-term support pledge](https://github.com/fluxcd/flux2/pull/3254) that went into effect with Flux 2.0.0 we need to make the Flux docs available for all supported versions (and likely older versions as well).

The goal is to have the docs for the most recent version available at https://fluxcd.io and the  2.0 docs available at https://v2-0.fluxcd.io.

- [x] https://github.com/fluxcd/website/issues/1534
- [x] https://github.com/fluxcd/helm-controller/pull/741
- [x] https://github.com/fluxcd/kustomize-controller/pull/929
- [x] https://github.com/fluxcd/notification-controller/pull/582
- [x] https://github.com/fluxcd/image-reflector-controller/pull/424
- [x] https://github.com/fluxcd/image-automation-controller/pull/563

**Comment by stefanprodan** [comment]
In v2.1 the docs structure will undergo a major transformation: https://github.com/fluxcd/website/pull/1573.

To preserver the current docs structure, I propose we start the versioning from v2.0.
