### ISSUE TITLE
Image Digest Reflection

### ISSUE THREAD

**Issue by makkes** [fluxcd/flux2#4245]
This is an umbrella issue to track work around image digest reflection:

- [ ] https://github.com/fluxcd/image-reflector-controller/issues/214
- [ ] https://github.com/fluxcd/image-reflector-controller/issues/87
- [ ] https://github.com/fluxcd/image-automation-controller/issues/165
- [ ] https://github.com/fluxcd/flux2/issues/4244
