### ISSUE TITLE
Prepare for Flux v2.1.2

### ISSUE THREAD

**Issue by stefanprodan** [fluxcd/flux2#4309]
Flux v2.1.2 is a patch release that comes with fixes and faster recovery time after a source-controller pod eviction.

:date: **Target dates:** 10-14 Oct 2023

Fixes:
- [x] https://github.com/fluxcd/source-controller/pull/1246
- [x] https://github.com/fluxcd/helm-controller/pull/785
- [x] https://github.com/fluxcd/helm-controller/pull/781
- [x] https://github.com/fluxcd/kustomize-controller/pull/980
- [x] https://github.com/fluxcd/kustomize-controller/pull/978
- [x] https://github.com/fluxcd/kustomize-controller/pull/983
- [x] https://github.com/fluxcd/flux2/pull/4324 
- [x] https://github.com/fluxcd/flux2/pull/4284

Release checklist:
- [x] source-controller v1.1.2
- [x] kustomize-controller v1.1.1
- [x] helm-controller v0.36.2
- [x] flux2 v2.1.2
- [x] terraform-provider-flux v1.1.2
