### ISSUE TITLE
Prepare for Flux v2.2.0

### ISSUE THREAD

**Issue by stefanprodan** [fluxcd/flux2#4410]
Flux 2.2.0 comes with new features, bug fixes and performance improvements. 

:date: **Target date:** 12 December 2023

This version updates the Flux components to: 
- Kubernetes v1.28
- Kustomize v5.3
- Helm v3.13
- Cosign v2.2 (Fix CVE-2023-46737)
- Go v1.21 (Fix CVE-2023-39326)
- Alpine v3.19

The Mean Time To Production benchmark results for this release can be found at [github.com/fluxcd/flux-benchmark](https://github.com/fluxcd/flux-benchmark/blob/main/RESULTS.md#flux-v220).

### API Promotions

- `HelmRelease` **v2beta2** (v2beta1 deprecated, scheduled for removal May 2024)
- Helm Drift detection and correction is no longer experimental (opt-in with `HelmRelease.spec.driftDetection` in **v2beta2**)
- `Alert` and `Provider` **v1beta3** (v1beta1 and v1beta2 deprecated, scheduled for removal May 2024)

### Features & Improvements

- Flux helm-controller's reconciliation model underwent a significant overhaul, addressing persistent issues such as the automatic recovery of releases stuck in a pending state. In addition, it improves the observability of the release status by reflecting more (historic) information in the status of the `HelmRelease` object. Lastly, it introduces the ability to enable drift detection on a per-object basis. This includes the option to ignore specific fields using Kustomize-like target selectors and JSON pointer paths.
- Flux helm-controller events & alerts have been extend to drift detection & correction and release uninstall.
- Flux source-controller allows identity matching for Cosign keyless verification for `OCIRepository` with `.spec.verify. matchOIDCIdentity `.
- Flux source-controller allows server-side filtering for `Bucket` with `.spec.prefix`. 
- Flux source-controller optimise syncing of GitHub PRs / GitLab MRs with shallow clones. 
- Flux source-controller allows pulling Helm OCI charts from insecure (non-TLS) container registries.
- Flux image-reflector-controller allows scanning image repos from insecure (non-TLS) container registries.
- Flux kustomize-controller GC will cleanup the pods belonging to stale Kubernetes Jobs at force apply. 
- Flux notification-controller adds support for Bitbucket Server & Data Center commit status updates.
- Flux notification-controller adds support for sending events to NATS.
- Flux CLI adds `--force` and `--reset` flags to `flux reconcile hr` for one-off install/upgrade of a failed Helm release.
- Flux CLI comes with support for bootstrapping Gitea repositories with `flux bootstrap gitea`.
- Flux CLI adds guardrails to `flux install` and `flux bootstrap` to protect users from destructive operations. 
- Flux CLI shows the in-cluster distribution version for `flux version` and `flux check`.

### TODOs

- https://github.com/fluxcd/helm-controller/pull/738
- https://github.com/fluxcd/helm-controller/pull/815
- https://github.com/fluxcd/helm-controller/pull/822
- https://github.com/fluxcd/notification-controller/issues/626
- https://github.com/fluxcd/notification-controller/pull/651
- https://github.com/fluxcd/source-controller/pull/1249
- https://github.com/fluxcd/source-controller/pull/1250
- https://github.com/fluxcd/source-controller/pull/1228
- https://github.com/fluxcd/source-controller/pull/1288
- https://github.com/fluxcd/flux2/pull/4270
- https://github.com/fluxcd/flux2/pull/4345
- https://github.com/fluxcd/flux2/pull/4355
- https://github.com/fluxcd/flux2/pull/4437
- https://github.com/fluxcd/flux2/pull/4424
- https://github.com/fluxcd/flux2/issues/3991
- https://github.com/fluxcd/flux2/issues/4432
- https://github.com/fluxcd/notification-controller/pull/639
- https://github.com/fluxcd/kustomize-controller/pull/997
- https://github.com/fluxcd/kustomize-controller/pull/1017
- https://github.com/fluxcd/image-reflector-controller/pull/472

### Release checklist

Releases:
- [x] source-controller v1.2.2
- [x] kustomize-controller v1.2.0
- [x] notification-controller v1.2.2
- [x] helm-controller: v0.37.0
- [x] image-reflector-controller v0.31.1
- [x] image-automation-controller v0.37.0
- [x] flux2 v2.2.0
- [x] terraform-provider-flux v1.2.0

Documentation:
- [x] Overhaul of `HelmRelease` API docs, examples and guides
- [x] Update all docs references to `HelmRelease` v2beta2
- [x] Update API docs and guides to `Alert` and `Provider` v1beta3
- [x] Update Kustomize version to 5.3.0 in docs and example scripts
- [x] Publish Flux release change log to GitHub & Slack
- [x] [Publish v2.2 docs](https://fluxcd.io/flux/releases/procedure/#distribution-minor-release-website)

**Comment by mewzherder** [comment]
Please add text that explains links to the blog post and upcoming meetup. Something like "For more details and context for this release, please read our blog post [ blog post url ]. Also, join Priyanka "Pinky" Ravi and Max Werner on Monday, December 18. They will give an overview of the release and answer your questions. [ meetup url https://www.meetup.com/weave-user-group/events/297818586/] thanks!
