### ISSUE TITLE
Prepare for Flux v2.2.1

### ISSUE THREAD

**Issue by stefanprodan** [fluxcd/flux2#4473]
Flux v2.2.1 is a patch release that comes with fixes to issues reported by users who upgraded to v2.2.0.

:date: **Target dates:** 13-15 Dec 2023

Fixes:
- [x] https://github.com/fluxcd/flux2/issues/4471
- [x] https://github.com/fluxcd/notification-controller/pull/683
- [x] https://github.com/fluxcd/notification-controller/issues/680
- [x] https://github.com/fluxcd/notification-controller/pull/682
- [x] https://github.com/fluxcd/notification-controller/issues/650
- [x] https://github.com/fluxcd/helm-controller/pull/844
- [x] https://github.com/fluxcd/helm-controller/pull/848
- [x] https://github.com/fluxcd/source-controller/pull/1324
- [x] https://github.com/fluxcd/flux2/issues/4472
- [x] https://github.com/fluxcd/flux2/issues/4470
- [x] https://github.com/fluxcd/flux2/issues/4474

Updates:
- [x] https://github.com/fluxcd/flux2/issues/4480
- [x] https://github.com/fluxcd/flux2/pull/4484 

Release checklist:
- [x] source-controller v1.2.3
- [x] kustomize-controller v1.2.1
- [x] notification-controller v1.2.3
- [x] helm-controller v0.37.1
- [x] flux2 v2.2.1
- [x] terraform-provider-flux v1.2.1
