### ISSUE TITLE
Prepare for Flux v2.2.3

### ISSUE THREAD

**Issue by stefanprodan** [fluxcd/flux2#4556]
Flux v2.2.3 is a patch release that comes with fixes to issues reported by users who upgraded to v2.2.

:date: **Target dates:** 1-5 Feb

Fixes:
- [x] https://github.com/fluxcd/kustomize-controller/issues/1041
- [x] https://github.com/fluxcd/flux2/issues/4509
- [x] https://github.com/fluxcd/pkg/issues/716
- [x] https://github.com/fluxcd/flux2/issues/4551
- [x] https://github.com/fluxcd/pkg/issues/715
- [x] https://github.com/fluxcd/notification-controller/issues/700
- [x] https://github.com/fluxcd/helm-controller/pull/884 

CVE Patches:
- [x] CVE-2023-45283 `Go stdlib`
- [x] CVE-2023-39326 `Go stdlib`
- [x] CVE-2023-49569 `github.com/go-git/go-git`
- [x] CVE-2023-48795 `golang.org/x/crypto`
- [x] GHSA-9763-4f94-gfch `github.com/cloudflare/circl`

Controller upgrades:
- [x] Go 1.21.6
- [x] Kubernetes 1.28.6 (`k8s.io/api`, `k8s.io/apimachinery`, `k8s.io/client-go`, etc)
- [x] https://github.com/fluxcd/flux2/issues/4562

Release checklist:
- [x] source-controller v1.2.4
- [x] kustomize-controller v1.2.2
- [x] notification-controller v1.2.4
- [x] helm-controller v0.37.4
- [x] image-reflector-controller v0.31.2
- [x] image-automation-controller 0.37.1
- [x] flux2 v2.2.3
- [x] terraform-provider-flux v1.2.3
