### ISSUE TITLE
Update Flux components to Go 1.22 and Kubernetes 1.29

### ISSUE THREAD

**Issue by stefanprodan** [fluxcd/flux2#4695]
Given that Flux dependencies require Go 1.22 (see https://github.com/fluxcd/notification-controller/pull/779) we need to update `go.mod`, CI workflows and  Dockerfiles across the FluxCD org. To align with upstream, we should also update controller-runtime, client-go, etc to match latest Kubernetes 1.29 release.

Projects:
- [x] cli-utils
- [x] pkg
- [x] go-git-providers
- [x] source-watcher
- [x] source-controller 
- [x] kustomize-controller 
- [x] notification-controller 
- [x] helm-controller
- [x] image-reflector-controller 
- [x] image-automation-controller
- [x] flux2
- [x] terraform-provider-flux
