### ISSUE TITLE
Prepare for Flux v2.3.0

### ISSUE THREAD

**Issue by stefanprodan** [fluxcd/flux2#4712]
Flux 2.3.0 promotes the Helm APIs to GA and comes with new features, bug fixes and performance improvements. 

:date: **Target dates:** 13-14 May

🚀  **Roadmap milestone:** https://fluxcd.io/roadmap/#v23-q2-2024

### API promotion

- [x] **HelmRelease** `helm.toolkit.fluxcd.io/v2` (v2beta2 deprecated)
- [x] **HelmRepository** `source.toolkit.fluxcd.io/v1` (v1beta2 deprecated)
- [x] **HelmChart** `source.toolkit.fluxcd.io/v1` (v1beta2 deprecated)
- [x] **ImageUpdateAutomation** `image.toolkit.fluxcd.io/v1beta2` (v1beta1 deprecated)

### Dependencies updates

- [x] Kubernetes 1.30
- [x] Go 1.22 
- [x] Kustomize 5.4
- [x] Helm 3.14
- [x] Cosign 2.2

### Release checklist

- [x] source-controller v1.3.0
- [x] kustomize-controller v1.3.0
- [x] notification-controller v1.3.0
- [x] helm-controller: v1.0.1
- [x] image-reflector-controller v0.32.0
- [x] image-automation-controller v0.38.0
- [x] flux-benchmark v2.3.0
- [x] flux2 v2.3.0
- [ ] terraform-provider-flux v1.3.0

###  Documentation

- [x] Update docs to promoted APIs
- [x] Publish Flux release change log to GitHub & Slack
- [x] [Publish v2.3 website](https://fluxcd.io/flux/releases/procedure/#distribution-minor-release-website)

### Conformance testing

| Distribution | Versions |
|:--------|:--------|
| Kubernetes KinD | 1.28.9, 1.29.4, 1.30.0 |
| OpenShift | 4.15.0-okd |
| K3s | 1.28.7,  1.29.2 | 
| Google Cloud | 1.28.7-gke.1026000 |

### TODO

- [x] https://github.com/fluxcd/source-controller/pull/1428
- [x] https://github.com/fluxcd/source-controller/issues/1391
- [x] https://github.com/fluxcd/source-controller/pull/1075
- [x] https://github.com/fluxcd/source-controller/pull/1412
- [x] https://github.com/fluxcd/kustomize-controller/pull/1129
- [x] https://github.com/fluxcd/kustomize-controller/pull/1130
- [x] https://github.com/fluxcd/kustomize-controller/issues/1133
- [x] https://github.com/fluxcd/flux2/issues/4601
- [x] https://github.com/fluxcd/notification-controller/pull/772
- [x] https://github.com/fluxcd/notification-controller/issues/745
- [x] https://github.com/fluxcd/notification-controller/pull/747
- [x] https://github.com/fluxcd/notification-controller/pull/795
- [x] https://github.com/fluxcd/helm-controller/pull/963
- [x] https://github.com/fluxcd/helm-controller/pull/879
- [x] https://github.com/fluxcd/helm-controller/pull/905
- [x] https://github.com/fluxcd/helm-controller/pull/968
- [x] https://github.com/fluxcd/helm-controller/issues/204
- [x] https://github.com/fluxcd/helm-controller/issues/922
- [x] https://github.com/fluxcd/helm-controller/issues/964
- [x] https://github.com/fluxcd/image-automation-controller/pull/619 
- [x] https://github.com/fluxcd/image-automation-controller/issues/437
- [x] https://github.com/fluxcd/image-automation-controller/issues/643
- [x] https://github.com/fluxcd/flux2/issues/4708
- [x] https://github.com/fluxcd/flux2/issues/4621
- [x] https://github.com/fluxcd/flux2/pull/4709 
- [x] https://github.com/fluxcd/flux2/issues/4692
- [x] https://github.com/fluxcd/flux2/issues/4695
- [x] https://github.com/fluxcd/flux2/issues/4700
- [x] https://github.com/fluxcd/flux2/pull/4717
- [x] https://github.com/fluxcd/flux2/pull/4728 
- [x] https://github.com/fluxcd/flux2/pull/4727 
- [x] https://github.com/fluxcd/flux2/pull/4769
- [x] https://github.com/fluxcd/flux2/issues/4760
- [x] https://github.com/fluxcd/flux2/issues/4761
- [x] https://github.com/fluxcd/terraform-provider-flux/issues/615
- [x] https://github.com/fluxcd/terraform-provider-flux/pull/661
- [x] https://github.com/fluxcd/terraform-provider-flux/pull/664
- [x] https://github.com/fluxcd/website/pull/1931

**Comment by siegenthalerroger** [comment]
Are release candidates being considered for these minor versions? Considering some of the issues found on the previous minor release, this might be a possible improvement. 

I'm happy to raise this in a discussion or on slack if that's preferable.

**Comment by stefanprodan** [comment]
> Are release candidates being considered for these minor versions?

Not with the current team of core maintainers. A release takes about 2 full days for 2-3 people. We just  don't have enough people to do work full-time on Flux.

**Comment by siegenthalerroger** [comment]
> > Are release candidates being considered for these minor versions?
> 
> Not with the current team of core maintainers. A release takes about 2 full days for 2-3 people. We just don't have enough people to do work full-time on Flux.

That's very understandable :)
