### ISSUE TITLE
Migrate CI to GitHub ARM64 Linux runners

### ISSUE THREAD

**Issue by stefanprodan** [fluxcd/flux2#4844]
GitHub now offers [ARM64 Linux](https://github.blog/changelog/2024-06-03-actions-arm-based-linux-and-windows-runners-are-now-in-public-beta/ ) runners so we can decommission the self-hosted Equinix ones.

Migrate workflows for:

- [x] flux2
- [x] flux-benchmark
- [x] source-controller
- [x] image-automation-controller

Decommission the Equinix machines:

- [x] equinix-arm-dc-1
- [x] equinix-arm-da-1
