### ISSUE TITLE
Build Flux components with Go 1.23

### ISSUE THREAD

**Issue by stefanprodan** [fluxcd/flux2#4927]
Update Go to 1.23 in Dockerfiles and GHA workflows.

Projects:
- [x] cli-utils
- [x] pkg
- [x] go-git-providers
- [x] source-watcher
- [x] source-controller 
- [x] kustomize-controller 
- [x] notification-controller 
- [x] helm-controller
- [x] image-reflector-controller 
- [x] image-automation-controller
- [x] flux2
- [x] terraform-provider-flux
