### ISSUE TITLE
Update Flux components to Kubernetes 1.31

### ISSUE THREAD

**Issue by stefanprodan** [fluxcd/flux2#4928]
Update the Kubernetes Go packages and adapt to the breaking changes in controller-runtime v0.19 in all Flux projects and run conformance for Kubernetes 1.31.0.

 Projects:
- [x] cli-utils
- [x] pkg
- [x] source-controller 
- [x] kustomize-controller 
- [x] notification-controller 
- [x] helm-controller
- [x] image-reflector-controller 
- [x] image-automation-controller
- [x] flux2
- [x] terraform-provider-flux
