### ISSUE TITLE
Prepare for Flux v2.4.0

### ISSUE THREAD

**Issue by stefanprodan** [fluxcd/flux2#4947]
Flux 2.4.0 promotes the Bucket API to GA and comes with new features, bug fixes and performance improvements. 

:date: **Target dates:** 30 September 

🚀  **Roadmap milestone:** https://fluxcd.io/roadmap/#v24-q3-2024

### Highlights

- Proxy support for container registries (OCIRepository, ImageRepository) and S3-compatible storage (Bucket)
- STS support for AWS and LDAP (Bucket)
- Teams notifications using the Microsoft Adaptive Card API (Alert Provider)
- Azure DevOps auth using OIDC and AKS Workload Identity (GitRepository, ImageUpdateAutomation)
- Adopt exiting in-cluster resources when reconciling releases (HelmRelease)

### API promotion

- [x] **Bucket** `source.toolkit.fluxcd.io/v1` (v1beta2 deprecated)

### Dependencies updates

- [x] Kubernetes 1.31
- [x] Go 1.23 
- [x] Helm 3.16
- [x] SOPS 3.9
- [x] Cosign 2.4
- [x] Notation 1.2

### Release checklist

- [x] source-controller v1.4.1
- [x] kustomize-controller v1.4.0
- [x] notification-controller v1.4.0
- [x] helm-controller: v1.1.0
- [x] image-reflector-controller v0.33.0
- [x] image-automation-controller v0.39.0
- [x] flux-benchmark v2.4.0
- [x] flux2 v2.4.0
- [x] terraform-provider-flux v1.4.0

###  Documentation

- [x] Update docs to promoted APIs
- [x] Publish Flux release change log to GitHub & Slack
- [x] [Publish v2.4 website](https://fluxcd.io/flux/releases/procedure/#distribution-minor-release-website)

### Conformance testing

| Distribution | Versions |
|:--------|:--------|
| Kubernetes KinD | 1.29.7, 1.30.2, 1.31.1 |
| OpenShift | 4.15.0-okd |
| K3s | 1.29.9, 1.30.5, 1.31.1 | 
| Google Cloud | 1.29.7-gke.1104000 |

### TODO

- [x] https://github.com/fluxcd/flux2/issues/4928
- [x] https://github.com/fluxcd/flux2/issues/4927
- [x] https://github.com/fluxcd/source-controller/issues/973 
- [x] https://github.com/fluxcd/source-controller/issues/1493
- [x] https://github.com/fluxcd/source-controller/issues/1563
- [x] https://github.com/fluxcd/source-controller/issues/1423
- [x] https://github.com/fluxcd/source-controller/issues/1564
- [x] https://github.com/fluxcd/source-controller/issues/1492
- [x] https://github.com/fluxcd/source-controller/pull/1516
- [x] https://github.com/fluxcd/source-controller/pull/1539
- [x] https://github.com/fluxcd/source-controller/pull/1592
- [x] https://github.com/fluxcd/source-controller/pull/1603
- [x] https://github.com/fluxcd/source-controller/pull/1591
- [x] https://github.com/fluxcd/image-automation-controller/pull/747
- [x] https://github.com/fluxcd/image-reflector-controller/pull/627
- [x] https://github.com/fluxcd/kustomize-controller/pull/1248
- [x] https://github.com/fluxcd/helm-controller/pull/1070
- [x] https://github.com/fluxcd/helm-controller/pull/990
- [x] https://github.com/fluxcd/helm-controller/pull/1010
- [x] https://github.com/fluxcd/helm-controller/pull/1060
- [x] https://github.com/fluxcd/helm-controller/pull/1062
- [x] https://github.com/fluxcd/helm-controller/pull/1068
- [x] https://github.com/fluxcd/kustomize-controller/pull/1212
- [x] https://github.com/fluxcd/notification-controller/pull/841
- [x] https://github.com/fluxcd/notification-controller/pull/829
- [x] https://github.com/fluxcd/notification-controller/pull/920
- [x] https://github.com/fluxcd/pkg/pull/808
- [x] https://github.com/fluxcd/pkg/pull/789
- [x] https://github.com/fluxcd/pkg/pull/793 
- [x] https://github.com/fluxcd/flux2/issues/4958
- [x] https://github.com/fluxcd/flux2/pull/4842
- [x] https://github.com/fluxcd/flux2/pull/4866
- [x] https://github.com/fluxcd/flux2/pull/4959
- [x] https://github.com/fluxcd/flux2/pull/4939
- [x] https://github.com/fluxcd/flux2/pull/4986
- [x] https://github.com/fluxcd/flux2/pull/5010
- [x] https://github.com/fluxcd/flux2/pull/5011
- [x] https://github.com/fluxcd/website/pull/2049
