### ISSUE TITLE
Remove deprecated object metrics from controllers

### ISSUE THREAD

**Issue by darkowlzz** [fluxcd/flux2#5083]
In Flux v2.1, the object metrics (suspend and readiness) were deprecated from the flux controllers. See the [deprecation notice](https://v2-1.docs.fluxcd.io/flux/monitoring/metrics/#warning-deprecated-resource-metrics) in the metrics docs. See https://github.com/fluxcd/flux2/issues/4128 for detailed motivation and the recommended metrics collection strategy.

Since then, the newly refactored controllers have removed the deprecated metrics: helm-controller and image-automation-controller.
The same should now be removed from the rest of the controllers.

The following lists the controllers that should remove the deprecated metrics, it also includes the reconcilers that record these metrics with reference links to a few of them in their respective controller repositories:

- [x] source-controller (for [GitRepository](https://github.com/fluxcd/source-controller/blob/v1.4.1/internal/controller/gitrepository_controller.go#L210-L211), Bucket, HelmRepository, HelmChart and OCIRepository)
- [x] kustomize-controller (for [Kustomization](https://github.com/fluxcd/kustomize-controller/blob/v1.4.0/internal/controller/kustomization_controller.go#L188-L190))
- [x] image-reflector-controller (for both [ImageRepository](https://github.com/fluxcd/image-reflector-controller/blob/v0.33.0/internal/controller/imagerepository_controller.go#L165-L166) and ImagePolicy)
- [x] notification-controller (for [Receiver](https://github.com/fluxcd/notification-controller/blob/v1.4.0/internal/controller/receiver_controller.go#L116-L118) only)

Following the above changes, the [metrics docs page](https://fluxcd.io/flux/monitoring/metrics/) should be updated accordingly:

- [x] Update metrics docs to remove the deprecation notice and alert at the top of the page ([metrics docs source](https://github.com/fluxcd/website/blob/269e3bcd79405e9032718fdbe06a34d6449fd291/content/en/flux/monitoring/metrics.md))

**Comment by stefanprodan** [comment]
To clarify, these are the deprecated metrics that are going to be removed:
- `gotk_reconcile_condition`
- `gotk_suspend_status`
