### ISSUE TITLE
Troubleshoot helpers for Helm release install/upgrade failures

### ISSUE THREAD

**Issue by stefanprodan** [fluxcd/flux2#5101]
To help users troubleshoot `HelmRelease` install and upgrade failures, we could add a new CLI command dedicated for debugging. 

### Specification

Introduce a new command called `flux debug helmrelease` that would help solve https://github.com/fluxcd/helm-controller/issues/497

### Debug values composition

The `flux debug helmrelease <name> --show-values` command could be used to print the final values by merging the `HelmRelease` inline values from `.spec.values` with the values coming from Kubernetes ConfigMaps/Secrets specified in `.spec.valuesFrom`. This command could help users debug failed releases by allowing them to export the final values from cluster into a local file. Using the final values, users can run locally `helm template --values in-cluster-values.yaml` and inspect the resulting resources. 

Note that the exported values may contain sensitive information extracted from Kubernetes Secrets, this should be highlighted in the command help docs to make users aware of the implications of running this command on untrusted machines. Give that the Flux CLI uses the local kubeConfig, only users with read access to the secrets will be able to run the debug command.

### Debug current status

The `flux debug helmrelease <name> --show-status` command can be used to print the release status along with the upgrade history, conditions and errors messages. This command could help users debug failed releases by inspecting the status sub-resource which contains rich informations about a HelmRelease compared to the `flux get helmreleaase` command which only displays the Ready condition message. 

## Implementation 

- [x] Extract the values composition logic from helm-controller to a shared Go package under `fluxcd/pkg/chartutil`
- [x] Refactor helm-controller to make use of the shared package from `fluxcd/pkg/chartutil`
- [ ] Implement `flux debug helmreleaase --show-values` using the shared package from `fluxcd/pkg/chartutil`
- [ ] Implement `flux debug helmreleaase --show-status`
- [ ] Document the command usage in the HelmRelease API docs.

PS. Refactoring the chartutil into a shared package is the first step towards `flux build helmrelease`.
