### ISSUE TITLE
Update Flux components to Kubernetes 1.32

### ISSUE THREAD

**Issue by stefanprodan** [fluxcd/flux2#5110]
Update the Kubernetes Go packages in all Flux projects and run conformance for Kubernetes 1.32.0. This update requires Go 1.23.0 in all go.mod, Dockerfile and GHA workflows. In addition Alpine must be set to 3.21 and `tonistiigi/xx` to 1.6.1 in all Dockerfiles.

 Projects:
- [x] cli-utils
- [x] pkg
- [x] source-controller 
- [x] kustomize-controller 
- [x] notification-controller 
- [x] helm-controller
- [x] image-reflector-controller 
- [x] image-automation-controller
- [x] flux2
- [x] terraform-provider-flux
