### ISSUE TITLE
Preparation for v0.8 release 

### ISSUE THREAD

**Issue by stefanprodan** [fluxcd/flux2#894]
Flux2 v0.8 release marks an important milestone ✨  **Feature Parity with Flux v1** ✨ 

### Documentation

- [x] Image automation migration guide (#806) 
- [x] Incident management for image automation (#871)
- [x] Advanced debugging guide (#878)
- [x] Azure ACR auth for image automation (#877)
- [x] Azure DevOps PAT auth for Git over HTTPS (#879)

### `flux` CLI

- [x] Rework `flux uninstall` to handle finalizers (#891)
- [x] Extend `flux create image policy` with regex filters and alphabetical ordering (#860)
- [x] Add support for getting resources by name (#867)
- [x] Allow Flux to be deployed on tainted Kubernetes nodes (#899)
- [x] Add certificate authority to `flux create source/secret git` (#874)

### source-controller

- [x] Self-singed cert support for Git over HTTPS (https://github.com/fluxcd/source-controller/pull/283)
- [x] Bug fix for Helm charts with custom valuesFile (https://github.com/fluxcd/source-controller/pull/286)
- [x] Bug fixes to `libgit2` Git implementation
	- [x] https://github.com/fluxcd/source-controller/pull/288
	- [x] https://github.com/fluxcd/source-controller/pull/290
- [x] Release v0.8.0 (Alpine 3.13, runtime profiling, EKS/IRSA support)

### kustomize-controller

- [x] Add support for bash-style variable substitutions (https://github.com/fluxcd/kustomize-controller/pull/253)
- [x] Extend the API with Kustomize Strategic Merge and JSON 6902 patches (https://github.com/fluxcd/kustomize-controller/pull/264)
- [x] Allow disabling pruning for certain resources (https://github.com/fluxcd/kustomize-controller/pull/267)
- [x] Release v0.8.0 (Alpine 3.13, runtime profiling support)

### helm-controller

- [x] Add PostRenderer support for Kustomize Strategic Merge, Images and JSON 6902 patches (https://github.com/fluxcd/helm-controller/pull/202)
- [x] Release v0.7.0 (Alpine 3.13, runtime profiling support)

### notification-controller

- [x] Add support for excluding events form alerting based on regular expressions (https://github.com/fluxcd/notification-controller/pull/138)
- [x] Release v0.8.0 (Alpine 3.13, runtime profiling support)

### image-reflector-controller

- [x] Extend image policy with numerical ordering (https://github.com/fluxcd/image-reflector-controller/issues/102)
- [x] Release v0.6.0 (Alpine 3.13, runtime profiling support)

### image-update-controller

- [x] Update to kyaml/v0.10.9 (https://github.com/fluxcd/image-automation-controller/pull/108)
- [x] Fix `libgit2` cloning bug (https://github.com/fluxcd/image-automation-controller/issues/106)
- [x] Release v0.6.0 (Alpine 3.13, runtime profiling support)

**Comment by stefanprodan** [comment]
flux2 v0.8 has been released 🎉  https://github.com/fluxcd/flux2/releases/tag/v0.8.0
